=== MarkusKun/sdlbuzzquiz/xml/quizconfig.dtd
<!ELEMENT gameconfig ((
  randomize_questions |
  randomize_answers   |
  preshow_answers     |
  allow_redecision    |
  reuse_questions     |
  scoring             |
  timing              |
  graphics            |
  import
  )*) >
  
<!ELEMENT randomize_questions (#PCDATA)> <!-- shuffle questions? -->
<!ELEMENT randomize_answers (#PCDATA)>  <!-- shuffle answers? -->
<!ELEMENT preshow_answers (#PCDATA)>    <!-- show all given answers before timeout? -->
<!ELEMENT allow_redecision (#PCDATA)>   <!-- allow switching answers? -->
<!ELEMENT reuse_questions (#PCDATA)>    <!-- insert questions after answering and deleting -->
<!ELEMENT import (#PCDATA)>           <!-- load another xml-file -->

<!ELEMENT scoring (correct*,incorrect*,nothing?,decay?)>

<!ELEMENT correct (#PCDATA)> <!-- points for correct answers (by order) -->
<!ELEMENT incorrect (#PCDATA)><!-- points for incorrect answers (by order) -->
<!ELEMENT nothing (#PCDATA)> <!-- points for not answering -->
<!ELEMENT decay (#PCDATA)> <!-- what points are worth (in percent) after one round) -->

<!ELEMENT timing (questionTime, answerTime, earlyFinish)>
<!ELEMENT questionTime (#PCDATA)> <!-- time for answering the question -->
<!ELEMENT answerTime (#PCDATA)> <!-- time that correct answer and points are displayed -->
<!ELEMENT earlyFinish (#PCDATA)> <!-- finish when all have answered -->

<!ELEMENT graphics (screenwidth, screenheight, fullscreen, fontsize*)>
<!ELEMENT screenwidth (#PCDATA)> 
<!ELEMENT screenheight (#PCDATA)>
<!ELEMENT fullscreen (#PCDATA)>

<!ELEMENT fontsize (#PCDATA)>
<!ATTLIST fontsize 
  type (default, question, answer, players, times, points) default>

=== MarkusKun/sdlbuzzquiz/xml/defaultconfig.xml
<?xml version="1.0" standalone="no"?>
<!DOCTYPE gameconfig SYSTEM "quizconfig.dtd">
<gameconfig>
  <randomize_questions>true</randomize_questions>
  <randomize_answers>true</randomize_answers>
  <preshow_answers>false</preshow_answers>
  <allow_redecision>false</allow_redecision>
  <reuse_questions>true</reuse_questions>

  <scoring>
    <correct>1000</correct>
    <correct>500</correct>
    <correct>250</correct>
    <correct>125</correct>
    <correct>100</correct>
    <incorrect>0</incorrect>
    <nothing>50</nothing>
    <decay>5</decay>
  </scoring>
  
  <timing>
    <questionTime>20</questionTime>
    <answerTime>6</answerTime>
    <earlyFinish>true</earlyFinish>
  </timing>
  
  <graphics>
    <screenwidth>1024</screenwidth>
    <screenheight>768</screenheight>
    <fullscreen>true</fullscreen>
    <fontsize>20</fontsize>
  </graphics>
   
  <import>./xml/questions.xml</import>
</gameconfig>
